### ISSUE TITLE
Maven dependency of jcenter?

### ISSUE THREAD

**Issue by Jerry0022** [Jerry0022/MixedFX#26]
What is the maven <dependency> of the bintray (jcenter) cloud:
https://bintray.com/marytts/marytts

Clicking on the setting up icon does help me with the repository but not with the dependency?!

Here is the file:
https://dl.bintray.com/marytts/marytts/de/dfki/mary/marytts-runtime/5.1.2/

**Comment by spike-rabbit** [comment]
JCenter hates his user. the only way to find out the maven coordinates is to reads to directory structure.
